# Generated by Django 2.2 on 2021-03-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='telefono',
        ),
        migrations.AddField(
            model_name='alumno',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
