# Generated by Django 2.2 on 2021-03-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=300)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('contrato', models.CharField(max_length=300)),
            ],
        ),
    ]
